### ISSUE TITLE
设置列为2，添加列表，高度自适应获取的高度异常不能使list元素展开，叠加在一起了

### ISSUE THREAD

**Issue by liliqd** [1977474741/vue-waterfall-rapid#16]

**Comment by 1977474741** [comment]
有使用element之类的框架吗，有的话在更新数据后重绘一下吧
this.$refs.waterfall.onRender = (e)=>{
      if(e.cause == 'data'){
        setTimeout(()=>{
          this.$refs.waterfall.repaints(0,0)
        },20)
      }
    }

**Comment by 1977474741** [comment]
`this.$refs.waterfall.onRender = (e)=>{
      if(e.cause == 'data'){
        setTimeout(()=>{
          this.$refs.waterfall.repaints(0,0)
        },20)
      }
    }`

**Comment by 1977474741** [comment]
有使用element之类的前端框架吗？有的话更新数据后再重绘一下吧。
this.$refs.waterfall.onRender = (e)=>{
  if(e.cause == 'data'){
    setTimeout(()=>{
      this.$refs.waterfall.repaints(0,0)
    },20)
  }
}
