### ISSUE TITLE
大佬你好，此插件似乎遇到了一点问题无法显示

### ISSUE THREAD

**Issue by 2975895077** [1977474741/vue-waterfall-rapid#19]
本地运行时正常显示，无报错信息
但是打包部署上线后报错并无法显示
![image](https://user-images.githubusercontent.com/51304626/168418122-ad05b36c-0601-498d-8d5f-de94a03b76b1.png)
求解答
项目使用了element-UI

**Comment by Sherlockouo** [comment]
兄弟，解决了嘛？

**Comment by 2975895077** [comment]
> 



> 兄弟，解决了嘛？

没有解决，源代码中尝试进行了修复，但未果；现已更换为 ‘vue-waterfall-plugin’
