### ISSUE TITLE
路由跳转到新页面，再返回，图片堆叠在一起，高度不正确

### ISSUE THREAD

**Issue by hike2008** [1977474741/vue-waterfall-rapid#23]
如图

<img width="279" alt="image" src="https://user-images.githubusercontent.com/8948629/223666067-7093a175-ca9a-4b3f-a92e-20dbcbbc6ded.png">

使用repaint重绘也不行

**Comment by 1977474741** [comment]
用的什么ui框架？

**Comment by hike2008** [comment]
vant

**Comment by 1977474741** [comment]
等ui框架渲染完后再repaint重绘试试，延迟一下

**Comment by hike2008** [comment]
试了不行，刷新加载的没问题，但是路由跳转新页面返回后，repaint依然会重叠

**Comment by hike2008** [comment]
> 

获取的高度变小了，看着是缓存图片的map问题，高度差正好是图片高度

<img width="314" alt="iShot2023-03-09 16 03 54" src="https://user-images.githubusercontent.com/8948629/223958851-a5a93991-86d5-4f06-ab11-c78213a6b6b5.png">

**Comment by hike2008** [comment]
> > 
> 
> 获取的高度变小了，看着是缓存图片的map问题，高度差正好是图片高度
> 
> <img alt="iShot2023-03-09 16 03 54" width="314" src="https://user-images.githubusercontent.com/8948629/223958851-a5a93991-86d5-4f06-ab11-c78213a6b6b5.png">

依据这个思路，我把这段逻辑注释掉，就正常显示了

<img width="510" alt="image" src="https://user-images.githubusercontent.com/8948629/223964232-219b3b3e-093e-4de7-9672-fb6e41e97668.png">

**Comment by 1977474741** [comment]
返回回来后，可以在页面显示的时候重绘一下
