### ISSUE TITLE
图片高度有问题重叠到一起了

### ISSUE THREAD

**Issue by w934423231** [1977474741/vue-waterfall-rapid#7]
![image](https://user-images.githubusercontent.com/38958128/115983140-12ad6200-a5d2-11eb-80dc-f5ee903c64e1.png)

**Comment by 1977474741** [comment]
能发个链接我看下吗

**Comment by w934423231** [comment]
我这个情况比较复杂，是在vue的dialog里使用的

**Comment by 1977474741** [comment]
QQ：1977474741

**Comment by w934423231** [comment]
我加您了

**Comment by 1977474741** [comment]
1.指定图片的Key（ imgKey="src"）
2.在img标签上加class（ class="waterfall-img"）
